apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-walk
  namespace: logging
  labels:
    k8s-app: log-walk
spec:
  selector:
    matchLabels:
      name: log-walk
  template:
    metadata:
      labels:
        k8s-app: log-walk
    spec:
      containers:
        - name: log-walk
          image: harbor.geniusafc.com/infra/log-walk:1.0.0
          command: ["/app/log-walk"]
          args: ["--work-hour=14", "--path=/logs", "--preserve-hour=1000", "--nap-time=50", "--dry-run"]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          volumeMounts:
            - name: cleanpath
              mountPath: /logs
      volumes:
        - name: cleanpath
          hostPath:
            path: /logs
        - name: systemdlog
          hostPath:
            path: /run/log/journal
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule